# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resultado.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ResultadoWindow(object):
    def setupUi(self, ResultadoWindow):
        ResultadoWindow.setObjectName("ResultadoWindow")
        ResultadoWindow.resize(886, 660)
        font = QtGui.QFont()
        font.setFamily("Miriam CLM")
        ResultadoWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(ResultadoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Busca = QtWidgets.QLabel(self.centralwidget)
        self.Busca.setGeometry(QtCore.QRect(30, 50, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Miriam CLM")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Busca.setFont(font)
        self.Busca.setObjectName("Busca")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 130, 521, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 170, 521, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 210, 521, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 250, 521, 41))
        font = QtGui.QFont()
        font.setFamily("Miriam CLM")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 140, 68, 19))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 180, 68, 19))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 220, 68, 19))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 260, 71, 19))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(50, 310, 791, 19))
        self.label_9.setObjectName("label_9")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(600, 240, 241, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(600, 140, 241, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(600, 190, 241, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_6.setPalette(palette)
        self.pushButton_6.setObjectName("pushButton_6")
        ResultadoWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ResultadoWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 886, 31))
        self.menubar.setObjectName("menubar")
        self.menuCadastro = QtWidgets.QMenu(self.menubar)
        self.menuCadastro.setObjectName("menuCadastro")
        ResultadoWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ResultadoWindow)
        self.statusbar.setObjectName("statusbar")
        ResultadoWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuCadastro.menuAction())

        self.retranslateUi(ResultadoWindow)
        QtCore.QMetaObject.connectSlotsByName(ResultadoWindow)

    def retranslateUi(self, ResultadoWindow):
        _translate = QtCore.QCoreApplication.translate
        ResultadoWindow.setWindowTitle(_translate("ResultadoWindow", "ResultadoWindow"))
        self.Busca.setText(_translate("ResultadoWindow", "Resultado: "))
        self.label.setText(_translate("ResultadoWindow", "Exemplo exemplar"))
        self.label_2.setText(_translate("ResultadoWindow", "Fulano de tal"))
        self.label_3.setText(_translate("ResultadoWindow", "2010"))
        self.label_4.setText(_translate("ResultadoWindow", "280"))
        self.label_5.setText(_translate("ResultadoWindow", "Título:"))
        self.label_6.setText(_translate("ResultadoWindow", "Autor(a):"))
        self.label_7.setText(_translate("ResultadoWindow", "Ano:"))
        self.label_8.setText(_translate("ResultadoWindow", "Páginas:"))
        self.label_9.setText(_translate("ResultadoWindow", "________________________________________________________________________________________________"))
        self.pushButton_4.setText(_translate("ResultadoWindow", "Voltar"))
        self.pushButton_5.setText(_translate("ResultadoWindow", "Alterar"))
        self.pushButton_6.setText(_translate("ResultadoWindow", "Excluir"))
        self.menuCadastro.setTitle(_translate("ResultadoWindow", "Buscar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ResultadoWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(ResultadoWindow)
    ResultadoWindow.show()
    sys.exit(app.exec_())

